### PR TITLE
Refine module auth

### PR DESCRIPTION
**Pull request by iMattPro**
The test fix should eliminate the random test failings

### CODE REVIEW

**Comment by iMattPro** [comment]
@paul999 What are your thoughts on the proposed changes to the two migration files? In particular, what would happen if we uncommented the erroneous line in the first migration file?

**Comment by paul999** [comment]
I would say if you umcomment, the other migration is technically direclty effectivly installed for new installs.
However, to keep in line with not changing migrations, I would say leave it out, as you already need to fix old installs. And for new installs it doesn't matter the if it is directly set correctly, or via the second migration.

**Comment by iMattPro** [comment]
> I would say if you umcomment, the other migration is technically direclty effectivly installed for new installs. However, to keep in line with not changing migrations, I would say leave it out, as you already need to fix old installs. And for new installs it doesn't matter the if it is directly set correctly, or via the second migration.

OK. I'll leave it in but commented out, just doing so to prevent anyone who might copy this code for themselves not make the same mistake we did by forgetting that line of code when we made that migration.

**Comment by paul999** [comment]
Yep, sounds good. Please mention it when submitting, so we don't forget we discussed it already.

**Review by rxu — APPROVED** [review]

**Pull request merged**
