### PR TITLE
Add ACP feature to subscribe "all" users to webpush notifications

### PR DESCRIPTION
**Pull request by rxu**

### CODE REVIEW

**Comment by rxu** [comment]
After creating this PR I've realized that this is impossible to implement at all when it comes to subscription itself. The latter is browser-dependent so you're unable to subscribe a user to receiving webpush without knowing what browser is used, hence can't generate endpoint URL.

**Comment by iMattPro** [comment]
My original thought about this, even before you brought this up, was maybe we just instead create a 1-time notification to users. A little popup message introducing the new feature with a link to their UCP/Notifications panel if they want to enable the feature themselves.

**Comment by rxu** [comment]
I suspect we could mimic `subscribeButtonHandler(event)` behavior (or even create a function from it) to request user a permission for sending webpush on 1st visit to a board. Didn't dig into it yet though.

**Comment by rxu** [comment]
> I suspect we could mimic `subscribeButtonHandler(event)` behavior

And this actually works, have to complete some more investigation in deep.

**Comment by iMattPro** [comment]
Not sure how I feel about this now. I'm not sure about having the web push JS being loaded on every single page all the time now. Initial thoughts are:
1. it should only be loaded like that if the Admin enabled this _subscribe all users_ option.
3. the SQL queries that would be loaded on every single page as a result of this change should probably be cached too. 

But ultimately I think this should be run by @marc1706 to see what his opinions may be. 

Also I still think we should be doing what the eventual core implementation is doing too, so the transition from 3.3 to 4.0 is seamless regarding this extension's functionality, so maybe it's only worth doing this if the 4.x core will do it too?

**Comment by iMattPro** [comment]
I think we can close this? 

I think the main problem with this is users when they Subscribe have to be asked by their browser if they want to allow push notifications. So subscribing should be an individual user action.

**Comment by rxu** [comment]
The main issue was that users have no idea they got a new feature of webpush so you need to let them know somehow. Hence as long as they get browser request they understand there's webpush now.

**Comment by iMattPro** [comment]
Yeah but thats annoying and invasive.

I still don't see it as an issue we should have to address for a couple reasons.

1. As an extension, admins add extensions all the time but users aren't forced by the extension to learn of it's new features. They either discover it or the admin makes it known to their users through maintenance updates for example.
2. In the core, when a board gets updated to 4.0 that'll be such a big change, it's again the admin's job to explain what's new after the update and for users to discover. But not the feature's job to make themselves known in an invasive way, right?

**Pull request closed without merging**
